### ISSUE TITLE
Application is not working.

### ISSUE THREAD

**Issue by dwivedi-ai** [Krrish105/IP-Address-Tracker#1]
# Application is not working.
## The landing page is blank
When I loaded the app, all the text fields (that were supposed to show information about my IP) were blank. Even after pasting my IP, the app was not able to show anything.
When I opened the console, these were the errors:
### Screenshot:
![Screenshot from 2022-02-26 22-59-20](https://user-images.githubusercontent.com/65527745/155853163-6c8bd19d-907f-43c8-aba3-63da74db6561.png)

**Comment by karishma-dev** [comment]
Yes.
I think this is not working for people with Adblock on their system.
I will try to fix it.
Thank you for noticing this!

**Comment by dwivedi-ai** [comment]
Hey, I got the problem... It's actually the browser that is blocking all the trackers. I am using brave browser, so it automatically blocks the ads and trackers. That is the reason why your application is unable to perform it's primary operation. I am sorry to bother you.
